### ISSUE TITLE
The Alert Maneuver request succeeds even though navigation is not supported

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/manticore#113]
When an `AlertManeuver` request is sent, the response should return `success = 0` since navigation is not currently supported on Manticore. Instead I received `success = 1`. 

This is the response I received for my sent  `AlertManeuver` request:

```
AlertManeuver (request), id: 7
{
    softButtons =     (
        "{\n    isHighlighted = 0;\n    softButtonID = 10;\n    text = Ok;\n    type = TEXT;\n}"
    );
    ttsChunks =     (
        "{\n    text = \"Go left\";\n    type = TEXT;\n}"
    );
}

AlertManeuver (response), id: 7
{
    info = "Navi is not supported by system";
    resultCode = "UNSUPPORTED_RESOURCE";
    success = 1;
}
```

**Comment by crokita** [comment]
After testing on generic_hmi and core on its own, this same result happens when allowing the functional group permitting this RPC for a connecting app, and Manticore allows all functional groups by default. It seems to be intentional that the RPC result is a success even though the RPC returns UNSUPPORTED_RESOURCE as a result code.

For now I'll mark this as expected behavior, although it is a bit strange that success is true.
