### ISSUE TITLE
Policy Server URL update does not trigger PTU

### ISSUE THREAD

**Issue by renonick87** [smartdevicelink/manticore#125]
It seems that the Manticore UI is sending the correct OnSystemRequest RPC to core to trigger a PTU when the URL is updated, but the PTU never reaches the Policy Server.
### Reproduction steps:
1. Start the policy server and host through ngrok.
1. Open a manticore instance.
1. Specify the Policy Server URL in manticore to point to the ngrok instance and the correct policy endpoint.
1. Press the Update Policy Server URL button.
#### Expected result:
1. Manticore will give some visual indication that the URL was updated in core and the next connected app will trigger a PTU that gets sent to the Policy Server.
#### Actual result:
1. There's no indicator that pressing the button did anything. No errors are logged. The Policy Server never gets a request.

**Comment by jordynmackool** [comment]
@renonick87 found this to not be an issue, per the below:

1. In sdl_core v6.1.1 a change was made that had core not attempt a PTU if there were no apps connected. This might just be specific to a certain build of core. do not retry ptu if no apps are connected ([#3350](https://github.com/smartdevicelink/sdl_core/pull/3351/commits/616abf28021b22acc2adb82fa8e2672b6a64fdac))
2. Since app policies for web apps are handled differently, the JS Suite is not built to handle the OnSystemRequest that core sends to initiate a PTU.
When I found this issue I either had no apps connected or only a JS app. After updating a JS app to be able to handle the request, the PTU was able to complete it.
