### ISSUE TITLE
App doesn't unregister form HMI

### ISSUE THREAD

**Issue by JulianKast** [smartdevicelink/manticore#153]
Summary: 
App doesn't unregister from HMI, if app is connected for at least 10 minutes.

Steps to replicate: 
- Connect app to manticore and open it
- wait 10 minutes,
- Delete app on phone.

Observed:
App stays on screen, you have to shut down an instance of manticore and start a new instance to get the same app to connect when you re-download/redeploy to phone

expected: 
App no longer appears on manticore, you can redeploy app to phone and get connected to manticore

**Comment by renonick87** [comment]
Unfortunately this is due to a setting in AWS that disconnects idle TCP connections after 350 seconds of inactivity. https://docs.aws.amazon.com/elasticloadbalancing/latest/network/network-load-balancers.html#connection-idle-timeout 
This setting cannot be modified. If this causes issues going forward, we suggest setting a keep-alive timer on the app side of the connection to something less than 350 seconds. The next manticore release will include a note on the manticore page with this suggestion.
https://gitlab.com/smartdevicelink/web/sdl-web/-/merge_requests/1396
